// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: remote_code_service.proto

package pb_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType2 int32

const (
	FileType2_project2 FileType2 = 0
	FileType2_codes2   FileType2 = 1
	FileType2_binary2  FileType2 = 2
)

// Enum value maps for FileType2.
var (
	FileType2_name = map[int32]string{
		0: "project2",
		1: "codes2",
		2: "binary2",
	}
	FileType2_value = map[string]int32{
		"project2": 0,
		"codes2":   1,
		"binary2":  2,
	}
)

func (x FileType2) Enum() *FileType2 {
	p := new(FileType2)
	*p = x
	return p
}

func (x FileType2) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType2) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_code_service_proto_enumTypes[0].Descriptor()
}

func (FileType2) Type() protoreflect.EnumType {
	return &file_remote_code_service_proto_enumTypes[0]
}

func (x FileType2) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType2.Descriptor instead.
func (FileType2) EnumDescriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{0}
}

//
//保证每个条目有uid message - struct
type HelloWorldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HelloText string `protobuf:"bytes,1,opt,name=hello_text,json=helloText,proto3" json:"hello_text,omitempty"`
}

func (x *HelloWorldRequest) Reset() {
	*x = HelloWorldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_code_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldRequest) ProtoMessage() {}

func (x *HelloWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldRequest.ProtoReflect.Descriptor instead.
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{0}
}

func (x *HelloWorldRequest) GetHelloText() string {
	if x != nil {
		return x.HelloText
	}
	return ""
}

type HelloWorldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThanksText string `protobuf:"bytes,1,opt,name=thanks_text,json=thanksText,proto3" json:"thanks_text,omitempty"`
}

func (x *HelloWorldResponse) Reset() {
	*x = HelloWorldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_code_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldResponse) ProtoMessage() {}

func (x *HelloWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldResponse.ProtoReflect.Descriptor instead.
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{1}
}

func (x *HelloWorldResponse) GetThanksText() string {
	if x != nil {
		return x.ThanksText
	}
	return ""
}

type DownloadRemoteCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//   string user_id = 1;
	Platform      string           `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	NoDeps        bool             `protobuf:"varint,3,opt,name=no_deps,json=noDeps,proto3" json:"no_deps,omitempty"`
	OnlyBinary    string           `protobuf:"bytes,4,opt,name=only_binary,json=onlyBinary,proto3" json:"only_binary,omitempty"`
	PythonVersion string           `protobuf:"bytes,5,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	Package       string           `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	Version       string           `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      *UploadMetadata2 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *DownloadRemoteCodeRequest) Reset() {
	*x = DownloadRemoteCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_code_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadRemoteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRemoteCodeRequest) ProtoMessage() {}

func (x *DownloadRemoteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRemoteCodeRequest.ProtoReflect.Descriptor instead.
func (*DownloadRemoteCodeRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadRemoteCodeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DownloadRemoteCodeRequest) GetNoDeps() bool {
	if x != nil {
		return x.NoDeps
	}
	return false
}

func (x *DownloadRemoteCodeRequest) GetOnlyBinary() string {
	if x != nil {
		return x.OnlyBinary
	}
	return ""
}

func (x *DownloadRemoteCodeRequest) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *DownloadRemoteCodeRequest) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *DownloadRemoteCodeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DownloadRemoteCodeRequest) GetMetadata() *UploadMetadata2 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DownloadRemoteCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message     string    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code        string    `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ProjectInfo *Project2 `protobuf:"bytes,3,opt,name=projectInfo,proto3" json:"projectInfo,omitempty"`
}

func (x *DownloadRemoteCodeResponse) Reset() {
	*x = DownloadRemoteCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_code_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadRemoteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRemoteCodeResponse) ProtoMessage() {}

func (x *DownloadRemoteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRemoteCodeResponse.ProtoReflect.Descriptor instead.
func (*DownloadRemoteCodeResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadRemoteCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DownloadRemoteCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DownloadRemoteCodeResponse) GetProjectInfo() *Project2 {
	if x != nil {
		return x.ProjectInfo
	}
	return nil
}

type DownloadAptDebRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//   string user_id = 1;
	Package  string           `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Version  string           `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Type     string           `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Metadata *UploadMetadata2 `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *DownloadAptDebRequest) Reset() {
	*x = DownloadAptDebRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_code_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadAptDebRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAptDebRequest) ProtoMessage() {}

func (x *DownloadAptDebRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAptDebRequest.ProtoReflect.Descriptor instead.
func (*DownloadAptDebRequest) Descriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadAptDebRequest) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *DownloadAptDebRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DownloadAptDebRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DownloadAptDebRequest) GetMetadata() *UploadMetadata2 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DownloadAptDebResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message     string    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code        string    `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ProjectInfo *Project2 `protobuf:"bytes,3,opt,name=projectInfo,proto3" json:"projectInfo,omitempty"`
}

func (x *DownloadAptDebResponse) Reset() {
	*x = DownloadAptDebResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_code_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadAptDebResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAptDebResponse) ProtoMessage() {}

func (x *DownloadAptDebResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAptDebResponse.ProtoReflect.Descriptor instead.
func (*DownloadAptDebResponse) Descriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadAptDebResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DownloadAptDebResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DownloadAptDebResponse) GetProjectInfo() *Project2 {
	if x != nil {
		return x.ProjectInfo
	}
	return nil
}

type FileInfo2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string    `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileType FileType2 `protobuf:"varint,2,opt,name=fileType,proto3,enum=pb.FileType2" json:"fileType,omitempty"`
}

func (x *FileInfo2) Reset() {
	*x = FileInfo2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_code_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo2) ProtoMessage() {}

func (x *FileInfo2) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo2.ProtoReflect.Descriptor instead.
func (*FileInfo2) Descriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{6}
}

func (x *FileInfo2) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo2) GetFileType() FileType2 {
	if x != nil {
		return x.FileType
	}
	return FileType2_project2
}

type UploadMetadata2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId uint64     `protobuf:"varint,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	UserId    uint64     `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	FileInfo  *FileInfo2 `protobuf:"bytes,3,opt,name=fileInfo,proto3" json:"fileInfo,omitempty"` //  FileType fileType = 4;
}

func (x *UploadMetadata2) Reset() {
	*x = UploadMetadata2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_code_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetadata2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata2) ProtoMessage() {}

func (x *UploadMetadata2) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata2.ProtoReflect.Descriptor instead.
func (*UploadMetadata2) Descriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{7}
}

func (x *UploadMetadata2) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *UploadMetadata2) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadMetadata2) GetFileInfo() *FileInfo2 {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

type Project2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectName        string                 `protobuf:"bytes,2,opt,name=projectName,proto3" json:"projectName,omitempty"`
	UserId             uint64                 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Tags               string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	License            string                 `protobuf:"bytes,5,opt,name=license,proto3" json:"license,omitempty"`
	Updatetime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatetime,proto3" json:"updatetime,omitempty"`
	ProjectDescription string                 `protobuf:"bytes,7,opt,name=projectDescription,proto3" json:"projectDescription,omitempty"`
	CodeAddr           string                 `protobuf:"bytes,8,opt,name=codeAddr,proto3" json:"codeAddr,omitempty"`
	BinaryAddr         string                 `protobuf:"bytes,9,opt,name=binaryAddr,proto3" json:"binaryAddr,omitempty"`
	Classifiers        uint32                 `protobuf:"varint,10,opt,name=classifiers,proto3" json:"classifiers,omitempty"`
}

func (x *Project2) Reset() {
	*x = Project2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remote_code_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Project2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project2) ProtoMessage() {}

func (x *Project2) ProtoReflect() protoreflect.Message {
	mi := &file_remote_code_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project2.ProtoReflect.Descriptor instead.
func (*Project2) Descriptor() ([]byte, []int) {
	return file_remote_code_service_proto_rawDescGZIP(), []int{8}
}

func (x *Project2) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project2) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *Project2) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Project2) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Project2) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *Project2) GetUpdatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Updatetime
	}
	return nil
}

func (x *Project2) GetProjectDescription() string {
	if x != nil {
		return x.ProjectDescription
	}
	return ""
}

func (x *Project2) GetCodeAddr() string {
	if x != nil {
		return x.CodeAddr
	}
	return ""
}

func (x *Project2) GetBinaryAddr() string {
	if x != nil {
		return x.BinaryAddr
	}
	return ""
}

func (x *Project2) GetClassifiers() uint32 {
	if x != nil {
		return x.Classifiers
	}
	return 0
}

var File_remote_code_service_proto protoreflect.FileDescriptor

var file_remote_code_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x32, 0x0a, 0x11, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x54, 0x65, 0x78, 0x74, 0x22, 0x35, 0x0a, 0x12, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x68,
	0x61, 0x6e, 0x6b, 0x73, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x68, 0x61, 0x6e, 0x6b, 0x73, 0x54, 0x65, 0x78, 0x74, 0x22, 0xfd, 0x01, 0x0a, 0x19,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x5f, 0x64, 0x65, 0x70, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6e, 0x6f, 0x44, 0x65, 0x70, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x6e, 0x6c, 0x79, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12,
	0x25, 0x0a, 0x0e, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x32, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7a, 0x0a, 0x1a, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x32, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x74, 0x44, 0x65, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x32,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x76, 0x0a, 0x16, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x74, 0x44, 0x65, 0x62, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x32, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x52, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x32, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x72, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x29, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x32,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xcc, 0x02, 0x0a, 0x08, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x41, 0x64, 0x64, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x2a, 0x32, 0x0a, 0x09, 0x46, 0x69, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x32, 0x12, 0x0c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x32, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x32, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x32, 0x10, 0x02, 0x32, 0xf4, 0x01,
	0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x55, 0x0a, 0x12, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0e, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x74, 0x44, 0x65, 0x62, 0x12, 0x19, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x74, 0x44, 0x65, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x74, 0x44, 0x65, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e,
	0x3b, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remote_code_service_proto_rawDescOnce sync.Once
	file_remote_code_service_proto_rawDescData = file_remote_code_service_proto_rawDesc
)

func file_remote_code_service_proto_rawDescGZIP() []byte {
	file_remote_code_service_proto_rawDescOnce.Do(func() {
		file_remote_code_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_remote_code_service_proto_rawDescData)
	})
	return file_remote_code_service_proto_rawDescData
}

var file_remote_code_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remote_code_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_remote_code_service_proto_goTypes = []interface{}{
	(FileType2)(0),                     // 0: pb.FileType2
	(*HelloWorldRequest)(nil),          // 1: pb.HelloWorldRequest
	(*HelloWorldResponse)(nil),         // 2: pb.HelloWorldResponse
	(*DownloadRemoteCodeRequest)(nil),  // 3: pb.DownloadRemoteCodeRequest
	(*DownloadRemoteCodeResponse)(nil), // 4: pb.DownloadRemoteCodeResponse
	(*DownloadAptDebRequest)(nil),      // 5: pb.DownloadAptDebRequest
	(*DownloadAptDebResponse)(nil),     // 6: pb.DownloadAptDebResponse
	(*FileInfo2)(nil),                  // 7: pb.FileInfo2
	(*UploadMetadata2)(nil),            // 8: pb.UploadMetadata2
	(*Project2)(nil),                   // 9: pb.Project2
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_remote_code_service_proto_depIdxs = []int32{
	8,  // 0: pb.DownloadRemoteCodeRequest.metadata:type_name -> pb.UploadMetadata2
	9,  // 1: pb.DownloadRemoteCodeResponse.projectInfo:type_name -> pb.Project2
	8,  // 2: pb.DownloadAptDebRequest.metadata:type_name -> pb.UploadMetadata2
	9,  // 3: pb.DownloadAptDebResponse.projectInfo:type_name -> pb.Project2
	0,  // 4: pb.FileInfo2.fileType:type_name -> pb.FileType2
	7,  // 5: pb.UploadMetadata2.fileInfo:type_name -> pb.FileInfo2
	10, // 6: pb.Project2.updatetime:type_name -> google.protobuf.Timestamp
	1,  // 7: pb.RemoteCodeService.HelloWorld:input_type -> pb.HelloWorldRequest
	3,  // 8: pb.RemoteCodeService.DownloadRemoteCode:input_type -> pb.DownloadRemoteCodeRequest
	5,  // 9: pb.RemoteCodeService.DownloadAptDeb:input_type -> pb.DownloadAptDebRequest
	2,  // 10: pb.RemoteCodeService.HelloWorld:output_type -> pb.HelloWorldResponse
	4,  // 11: pb.RemoteCodeService.DownloadRemoteCode:output_type -> pb.DownloadRemoteCodeResponse
	6,  // 12: pb.RemoteCodeService.DownloadAptDeb:output_type -> pb.DownloadAptDebResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_remote_code_service_proto_init() }
func file_remote_code_service_proto_init() {
	if File_remote_code_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remote_code_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_code_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_code_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadRemoteCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_code_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadRemoteCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_code_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadAptDebRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_code_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadAptDebResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_code_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_code_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetadata2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remote_code_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Project2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remote_code_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_code_service_proto_goTypes,
		DependencyIndexes: file_remote_code_service_proto_depIdxs,
		EnumInfos:         file_remote_code_service_proto_enumTypes,
		MessageInfos:      file_remote_code_service_proto_msgTypes,
	}.Build()
	File_remote_code_service_proto = out.File
	file_remote_code_service_proto_rawDesc = nil
	file_remote_code_service_proto_goTypes = nil
	file_remote_code_service_proto_depIdxs = nil
}
